# name: CodeCov

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@main
#     - uses: codecov/codecov-action@v3
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#     - name: Generate report
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest pandas pdoc3 mslib streamlit psycopg2
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#         coverage run test/item_manager_test.py
#         coverage run test/test_account_info.py
#         coverage xml
#     - name: Upload coverage reports to Codecov
#       uses: codecov/codecov-action@v3
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
